### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ikamensh** [datasets/finance-vix#6]
```
# Run the script
python flows/finance-vix.py
```
I am assuming this is something to do after cloning this repository? There is no directory `flows`.

**Comment by HallowedDust5** [comment]
No, it doesn't have anything to do with cloning the repo. They just don't have a `flows` directory. I'm assuming you would run `finance-vix-flows.py` in the top level directory. Also, I think the repo just isn't maintained anymore. Last commit is from 5 years ago.

**Comment by rufuspollock** [comment]
@HallowedDust5 we do want to maintain this - we just need to fix the automation (and true it is has been a long time we wanted to do that).

NB: we accept pull requests 😄

**Comment by rufuspollock** [comment]
@davidgasquez would you be up for having a look at fixing this one? it's a good example of building a simple automated pipeline 😄

**Comment by HallowedDust5** [comment]
@rufuspollock What type of automation? Like automating dependency updates or something else? I just stumbled across this repo while doing research so I don't exactly remember what it's for

**Comment by rufuspollock** [comment]
@HallowedDust5 it would just be getting the scraping script working again and then setting up a github action to run it once a day or similar ...

**Comment by davidgasquez** [comment]
From a quick look, seems the _Resource_ is now under a [new URL path](https://www.cboe.com/tradable_products/vix/vix_historical_data/).

This repo might be worth revisiting and simplifying. Will see if I have some time during this break.

**Comment by rufuspollock** [comment]
@davidgasquez 👍🙏
